spring.application.name=Zenith
server.port=8085
# Configuração do H2 Database
spring.datasource.url=jdbc:h2:mem:zenithdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do JPA / Hibernate (Persistência)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console